id: 1772736104102-ui
title: ui继续修复
description: >-
  1. task页面创建worktree时，只有两个框，没有中文表示是什么框，先在需要三个框，分别是 从哪个分支创建
  、worktree分支、worktree路径; 

  2. task页面 description 做成类似markdone那样富文本的编辑器，好看一点 

  3. task页面的对话框，目前看好像没有使用 git worktree -b 创建worktree分支，进到终端时还是在项目根目录下，需要改成 git
  worktree -b ,并且 cd worktree目录下 

  4. task的终端界面UI，做的更现代化一点，支持tab/ctrl/shift各种快捷操作，文字的ui渲染可以参考mac里.zshrc风格; 

  5. task页面编辑任务时，不支持修改 milestone
description_file: null
status: done
priority: high
milestone_id: m1
parent_tasks: []
labels:
  - ui
  - agent
  - terminal
created_at: '2026-03-05T18:41:44.103Z'
updated_at: '2026-03-06T01:29:03.932Z'
created_by: web
agent:
  assigned: false
  identity: null
  assigned_at: null
  session_id: null
  status: null
terminal:
  enabled: false
  mode: local
  session_id: null
  status: stopped
  host: null
  port: 22
  username: null
  timeout_days: 3
  auto_stop_on_task_done: true
  started_at: '2026-03-05T19:12:24.897Z'
  last_active_at: '2026-03-05T19:12:58.927Z'
  stopped_at: '2026-03-05T19:13:00.434Z'
  stop_reason: manual
  exit_code: 0
  exit_signal: 9
git:
  branch: 1772736104102-ui
  commits: []
  source_branch: master
