id: 1773028025857-ui
title: ui优化
description: |
  项目页面 分成多个页面，第一页为milestone, 第二页为task列表，task列表，支持多个筛选，按laberl/完成状态/milestone;
  milestone页面除了展示目标外，还需要展示任务状态: 所属所有任务的完成进度，按照优先级排序的任务的进度，只展示完成进度就行，不用展示具体的task；
  task页面支持排序功能，按照时间先后、优先级状态排序；
  task的id时间戳需要显示出来，规则是name-timestramp,比如ui-2026-03-09-11-49; 
description_file: null
status: todo
priority: high
milestone_id: m1
parent_tasks: []
labels:
  - ui
created_at: '2026-03-09T03:47:05.857Z'
updated_at: '2026-03-09T03:50:37.426Z'
created_by: web
agent:
  assigned: false
  identity: null
  assigned_at: null
  session_id: null
  status: null
terminal:
  enabled: false
  mode: null
  session_id: null
  status: stopped
  host: null
  port: 22
  username: null
  timeout_days: 3
  auto_stop_on_task_done: true
  started_at: null
  last_active_at: null
  stopped_at: null
  stop_reason: null
git:
  branch: 1773028025857-ui
  commits: []
  source_branch: null
