id: 1773036415833-
title: 修复启动脚本和终止脚本
description: |-
  1. 启动脚本应当改为后台常驻，不依赖终端是否启动
  2. 终止脚本增加一个指令，检测当前用户的所有端口是否启动了xtask相关进程并全部关闭；
description_file: null
status: todo
priority: critical
milestone_id: m2
parent_tasks: []
labels:
  - terminal
created_at: '2026-03-09T06:06:55.833Z'
updated_at: '2026-03-09T06:20:01.687Z'
created_by: web
agent:
  assigned: false
  identity: null
  assigned_at: null
  session_id: null
  status: null
terminal:
  enabled: true
  mode: local
  session_id: 1773036415833--terminal-1773036440690
  status: running
  host: null
  port: 22
  username: null
  timeout_days: 3
  auto_stop_on_task_done: true
  started_at: '2026-03-09T06:07:20.690Z'
  last_active_at: '2026-03-09T06:07:20.690Z'
  stopped_at: null
  stop_reason: null
git:
  branch: 1773036415833-scripts
  commits: []
  source_branch: null
