id: 1773124373867-xtask-ui
title: xtask 任务页ui 优化
description: |
  - xtask 任务页 排序 应当做到页面的上方，而不是左侧，页面上方排序方式应当支持 按照任务优先级，时间，名称；并且都支持正序和倒序
  - xtask 任务页 筛选 的按钮在左侧，筛选标签时，支持多选，应当展示一行多个，并且不同标签颜色不同，在task页面渲染时都能看到
  - xtask返回到上一级页面时，应当返回到任务那一栏；而不是milestones;
description_file: null
summary_file: null
status: todo
priority: high
milestone_id: m1
parent_tasks: []
labels:
  - ui
  - xtask
created_at: '2026-03-10T06:32:53.867Z'
updated_at: '2026-03-10T06:34:08.734Z'
created_by: web
agent:
  assigned: false
  identity: null
  assigned_at: null
  session_id: null
  status: null
terminal:
  enabled: true
  mode: local
  session_id: 1773124373867-xtask-ui-terminal-1773124448734
  status: running
  host: null
  port: 22
  username: null
  timeout_days: 3
  auto_stop_on_task_done: true
  started_at: '2026-03-10T06:34:08.734Z'
  last_active_at: '2026-03-10T06:34:08.734Z'
  stopped_at: null
  stop_reason: null
git:
  branch: 1773124373867-xtask-ui
  commits: []
  source_branch: null
