id: 1773395323882-xtask-cli
title: xtask cli支持新的功能
description: |-
  - xtask cli 支持更新已有的summary.md到对应的 ref-xtask 结构下
  - xtask cli 支持查找当前分支任务，并回显的功能
description_file: null
summary_file: null
status: done
priority: high
milestone_id: m1
parent_tasks: []
labels:
  - xtask
  - cli
created_at: '2026-03-13T09:48:43.882Z'
updated_at: '2026-03-13T10:07:59.875Z'
created_by: web
agent:
  assigned: false
  identity: null
  assigned_at: null
  session_id: null
  status: null
terminal:
  enabled: true
  mode: local
  session_id: 1773395323882-xtask-cli-terminal-1773395331475
  status: running
  host: null
  port: 22
  username: null
  timeout_days: 3
  auto_stop_on_task_done: true
  started_at: '2026-03-13T09:48:51.475Z'
  last_active_at: '2026-03-13T09:48:51.475Z'
  stopped_at: null
  stop_reason: null
git:
  branch: 1773395323882-xtask-cli
  commits: []
  source_branch: null
