id: 2026-03-20-16-55-25-175-task-kk1s
title: 测试
description: 测试
description_file: null
summary_file: null
status: todo
priority: high
milestone_id: m1
parent_tasks: []
labels: []
created_at: '2026-03-20T08:55:25.176Z'
updated_at: '2026-03-20T08:58:15.968Z'
created_by: web
agent:
  assigned: false
  identity: null
  assigned_at: null
  session_id: null
  status: null
terminal:
  enabled: true
  mode: local
  session_id: 2026-03-20-16-55-25-175-task-kk1s-terminal-1773997095968
  status: running
  host: null
  port: 22
  username: null
  timeout_days: 3
  auto_stop_on_task_done: true
  started_at: '2026-03-20T08:58:15.968Z'
  last_active_at: '2026-03-20T08:58:15.968Z'
  stopped_at: null
  stop_reason: null
git:
  branch: 2026-03-20-16-55-25-175-task-kk1s
  commits: []
  source_branch: master
