id: 1773047051811-task-yml
title: task.yml增加字段
description: |
  task.yml 新增一个用于描述总结的字段，Agent完成任务后必须写入该文件；
  task页面上检测到该总结文档后，展示在description下方，静态刷新的方式或者3min检测一次;
  对于description文档，如果文档内容过长，超过一定字数和行数，就自动放到某个文件下面;
description_file: null
status: todo
priority: high
milestone_id: m2
parent_tasks: []
labels:
  - ui
  - terminal
created_at: '2026-03-09T09:04:11.811Z'
updated_at: '2026-03-09T09:04:45.141Z'
created_by: web
agent:
  assigned: false
  identity: null
  assigned_at: null
  session_id: null
  status: null
terminal:
  enabled: true
  mode: local
  session_id: 1773047051811-task-yml-terminal-1773047085140
  status: running
  host: null
  port: 22
  username: null
  timeout_days: 3
  auto_stop_on_task_done: true
  started_at: '2026-03-09T09:04:45.140Z'
  last_active_at: '2026-03-09T09:04:45.140Z'
  stopped_at: null
  stop_reason: null
git:
  branch: 1773047051811-task-yml
  commits: []
  source_branch: null
