id: 1772696309362-
title: 设计
description: ''
status: todo
priority: critical
milestone_id: null
parent_tasks: []
labels: []
created_at: '2026-03-05T07:38:29.362Z'
updated_at: '2026-03-05T07:38:29.362Z'
created_by: web
agent:
  assigned: false
  identity: null
  assigned_at: null
  status: null
git:
  branch: null
  commits: []
