id: 1773732575353-task-description
title: 新建任务的分支名时应当显示以视角戳-{task description} 命名
description: ''
description_file: null
summary_file: null
status: todo
priority: critical
milestone_id: m2
parent_tasks: []
labels:
  - xtask
created_at: '2026-03-17T07:29:35.353Z'
updated_at: '2026-03-17T07:29:47.217Z'
created_by: web
agent:
  assigned: false
  identity: null
  assigned_at: null
  session_id: null
  status: null
terminal:
  enabled: true
  mode: local
  session_id: 1773732575353-task-description-terminal-1773732587217
  status: running
  host: null
  port: 22
  username: null
  timeout_days: 3
  auto_stop_on_task_done: true
  started_at: '2026-03-17T07:29:47.217Z'
  last_active_at: '2026-03-17T07:29:47.217Z'
  stopped_at: null
  stop_reason: null
git:
  branch: 1773732575353-task-description
  commits: []
  source_branch: master
